const RUNE_DATA = [
      {num: 1, name: "El", clvl: 11, weapon: "+50 AR, +1 Light Radius", armor: "+1 Light Radius, +15 Defense", countess: ["N","NM","H"]},
      {num: 2, name: "Eld", clvl: 11, weapon: "+75% Damage vs. Undead, +50 AR vs. Undead", armor: "Lowers Stamina drain by 15%", shield: "+7% Blocking", countess: ["N","NM","H"]},
      {num: 3, name: "Tir", clvl: 13, weapon: "+2 Mana Per Kill", armor: "+2 Mana Per Kill", countess: ["N","NM","H"]},
      {num: 4, name: "Nef", clvl: 13, weapon: "Knockback", armor: "+30 Defense vs. Missile", countess: ["N","NM","H"]},
      {num: 5, name: "Eth", clvl: 15, weapon: "-25% Target Defense", armor: "Regenerate Mana 15%", countess: ["N","NM","H"]},
      {num: 6, name: "Ith", clvl: 15, weapon: "+9 to Maximum Damage", armor: "15% Damage Taken Goes to Mana", countess: ["N","NM","H"]},
      {num: 7, name: "Tal", clvl: 17, weapon: "75 Poison damage over 5 seconds", armor: "+30% Poison Resistance", shield: "+35% Poison Resistance", countess: ["N","NM","H"]},
      {num: 8, name: "Ral", clvl: 19, weapon: "+5-30 Fire Damage", armor: "+30% Fire Resistance", shield: "+35% Fire Resistance", countess: ["N","NM","H"]},
      {num: 9, name: "Ort", clvl: 21, weapon: "+1-50 Lightning Damage", armor: "+30% Lightning Resistance", shield: "+35% Lightning Resistance", countess: ["NM","H"]},
      {num: 10, name: "Thul", clvl: 23, weapon: "+3-14 Cold Damage (3 sec)", armor: "+30% Cold Resistance", shield: "+35% Cold Resistance", countess: ["NM","H"]},
      {num: 11, name: "Amn", clvl: 25, weapon: "7% Life Stolen Per Hit", armor: "Attacker takes 14 damage", countess: ["NM","H"]},
      {num: 12, name: "Sol", clvl: 27, weapon: "+9 to Minimum Damage", armor: "-7 Damage Taken", countess: ["NM","H"]},
      {num: 13, name: "Shael", clvl: 29, weapon: "+20% Faster Attack Rate", armor: "+20% Faster Hit Recovery", shield: "+20% Faster Block Rate", countess: ["NM","H"]},
      {num: 14, name: "Dol", clvl: 31, weapon: "25% Chance Hit Causes Monster to Flee", armor: "+7 Replenish Life", countess: ["NM","H"]},
      {num: 15, name: "Hel", clvl: 0, weapon: "-20% Requirements", armor: "-15% Requirements", countess: ["NM","H"]},
      {num: 16, name: "Io", clvl: 35, weapon: "+10 Vitality", armor: "+10 Vitality", countess: ["NM","H"]},
      {num: 17, name: "Lum", clvl: 37, weapon: "+10 Energy", armor: "+10 Energy", countess: ["H"]},
      {num: 18, name: "Ko", clvl: 39, weapon: "+10 Dexterity", armor: "+10 Dexterity", countess: ["H"]},
      {num: 19, name: "Fal", clvl: 41, weapon: "+10 Strength", armor: "+10 Strength", countess: ["H"]},
      {num: 20, name: "Lem", clvl: 43, weapon: "+75% Extra Gold from Monsters", armor: "+50% Extra Gold from Monsters", countess: ["H"]},
      {num: 21, name: "Pul", clvl: 45, weapon: "+75% Damage to Demons, +100 AR vs. Demons", armor: "+30% Defense", countess: ["H"]},
      {num: 22, name: "Um", clvl: 47, weapon: "25% Chance of Open Wounds", armor: "+15% Resist All", shield: "+22% Resist All", countess: ["H"]},
      {num: 23, name: "Mal", clvl: 49, weapon: "Prevent Monster Healing", armor: "Reduce Magic Damage by 7", countess: ["H"]},
      {num: 24, name: "Ist", clvl: 51, weapon: "+30% Better Chance Finding Magic Items", armor: "+25% Better Chance Finding Magic Items", countess: ["H"]},
      {num: 25, name: "Gul", clvl: 53, weapon: "+20% AR", armor: "+5 to Max Resist Poison", countess: []},
      {num: 26, name: "Vex", clvl: 55, weapon: "7% Mana Leech", armor: "+5 to Max Fire Resist", countess: []},
      {num: 27, name: "Ohm", clvl: 57, weapon: "+50% Damage", armor: "+5 to Max Resist Cold", countess: []},
      {num: 28, name: "Lo", clvl: 59, weapon: "20% Chance of Deadly Strike", armor: "+5 to Max Resist Lightning", countess: []},
      {num: 29, name: "Sur", clvl: 61, weapon: "20% Chance Hit Blinds Target", armor: "+5% total Mana", shield: "+50 Mana", countess: []},
      {num: 30, name: "Ber", clvl: 63, weapon: "20% Chance of Crushing Blow", armor: "Damage Reduced by 8%", countess: []},
      {num: 31, name: "Jah", clvl: 65, weapon: "Ignores Target Defense", armor: "+5% of total Hit Points", shield: "+50 Hit Points", countess: []},
      {num: 32, name: "Cham", clvl: 67, weapon: "32% Chance Hit Freezing Target (3 sec)", armor: "Cannot be Frozen", countess: []},
      {num: 33, name: "Zod", clvl: 69, weapon: "Indestructible", armor: "Indestructible", countess: []}
    ];
